version: '3'
services:
  local-rabbit-mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  zoom-meeting-service:
    build:
      context: ./zoom-meeting-service
      dockerfile: Dockerfile
    expose:
      - 8080
    container_name: zoom-meeting-service
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
