spring:
  application:
    name: auth-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        prefer-ip-address: false
        health-check-path: /actuator/health
        health-check-interval: 10s

  datasource:
    url: ${AUTH_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/authdb}
    username: ${AUTH_SPRING_DATASOURCE_USERNAME:postgres}
    password: ${AUTH_SPRING_DATASOURCE_PASSWORD:postgres}

  liquibase:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

server:
  port: 8080

auth:
  jwt:
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 30
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}

bot:
  link: t.me/calendorny_bot
  link-length: 10
