spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task/**

server:
  port: 8080
